### ISSUE TITLE
Accessibility Dimension Factors (Adjust Thresholds)

### ISSUE THREAD

**Issue by carolinamayh** [kartoza/GEEST#67] opened 2024-07-11 12:10 UTC
The five Accessibility Dimension factors required for the new version of the tool are already included in the previous version. However, the suggested thresholds for calculating the catchment areas for each factor have been updated. These changes need to be reflected under each respective factor. Please refer to the Excel file to review the suggested thresholds for each factor.

**Comment by ClaraIV** [comment] 2024-07-15 08:06
@osundwajeff Hi Jeff, could you please confirm that you managed to adjust the thresholds to all existing factors in the Accessibility Dimension? I see them listed separately in the "Needs Review" and I'd like to close this ticket if it has been addressed. Thanks!

**Comment by osundwajeff** [comment] 2024-07-15 08:26
Hi @ClaraIV, yes I managed to adjust them. The changes are in the current draft 
PR

**Comment by dragosgontariu** [comment] 2024-07-15 13:22
@osundwajeff  Hi Jeff, I've tested the updates and none of the factors could be processed due to the attached errors:

[Accessibility errors.zip](https://github.com/user-attachments/files/16235056/Accessibility.errors.zip)

Could you investigate these? Thanks!

**Comment by osundwajeff** [comment] 2024-07-15 13:25
Thanks for the feedback @dragosgontariu . I'll take a look at them.

**Comment by osundwajeff** [comment] 2024-07-17 07:22
Hi @dragosgontariu, I haven't been able to reproduce this error. Can we maybe have a session to look at it?

**Comment by dragosgontariu** [comment] 2024-07-17 07:27
@osundwajeff Hi Jeff, Sure, let's have a call. Can you forward me an invite?

**Comment by osundwajeff** [comment] 2024-07-17 11:44
@dragosgontariu I have a probable fix for those errors. I have pushed the changes to that PR, maybe you can test to see if you are still getting that issue

**Comment by osundwajeff** [comment] 2024-07-17 11:58
@dragosgontariu I think you can use it from this branch https://github.com/osundwajeff/GEEST/tree/dev-work

**Comment by javaftw** [comment] 2024-07-19 13:22
@dragosgontariu Hi!
We are having some trouble replicating the "File not found" issue mentioned [here](https://github.com/kartoza/GEEST/issues/67#issuecomment-2228496223), and would appreciate it if you could share as much of the following information as possible:
- Versions (OS, QGIS, plugin, Python, etc)
- File paths (installation, plugin, input, output, etc.)
- Copy of offending source files
- List of steps taken to raise error
- Copies of stack traces/error reports
- Notes on error consistency/reproducibility

**Comment by dragosgontariu** [comment] 2024-07-19 14:17
@osundwajeff

Hi Jeff,
As per your request please find below my response:

•	Versions (OS, QGIS, plugin, Python, etc)

Windows 10 Pro
QGIS 3.32 – Lima
The updated plugin from the PR on 18.08.2024 – now I see there are other updates
Python 3.9.0
The ORS service is working with the API key provided by them

•	File paths (installation, plugin, input, output, etc.)

The input files are attached here. 
[ETF.zip](https://github.com/user-attachments/files/16313161/ETF.zip)
[FIN.zip](https://github.com/user-attachments/files/16313162/FIN.zip)
[HLT.zip](https://github.com/user-attachments/files/16313163/HLT.zip)
[PBT.zip](https://github.com/user-attachments/files/16313164/PBT.zip)
[WTP.zip](https://github.com/user-attachments/files/16313165/WTP.zip)
[Admin0.zip](https://github.com/user-attachments/files/16313169/Admin0.zip)

The output directory it’s for testing.
The CRS used is EPSG: 32620

•	Copy of offending source files
•	List of steps taken to raise error
•	Copies of stack traces/error reports
•	Notes on error consistency/reproducibility

All the files generated in the process are attached here.
[output.zip](https://github.com/user-attachments/files/16313110/output.zip)

**Comment by javaftw** [comment] 2024-07-19 14:37
Thanks @dragosgontariu , this is very helpful indeed.
I would appreciate it if you could pass on some log files (typically found at` C:\Users\<YourUsername>\AppData\Local\QGIS\QGIS3\profiles\default\QGIS\QGIS3\logs`) that would have captured any error messages during the operation that fails to produce the .shp files. Thanks in advance.

**Comment by dragosgontariu** [comment] 2024-07-19 14:44
Sure @osundwajeff 
This is what I have there:

![image](https://github.com/user-attachments/assets/f260f7ec-46e3-45eb-977a-da33ea6d267b)


[crashes.zip](https://github.com/user-attachments/files/16313541/crashes.zip)

**Comment by javaftw** [comment] 2024-07-19 14:53
Ah, processing logging has to be explicitly enabled, which is wasn't. Nevermind. Thanks anyway.

**Comment by dragosgontariu** [comment] 2024-07-20 13:01
@osundwajeff @ClaraIV @carolinamayh 

Hi Jeff,

I tried to tag Michelle as well but I didn't find her in the list.

I noticed a new update in the repository and gave it a chance—the one where you can input all four shapefiles for Women’s Travel Patterns—and this time, all the factors in the Accessibility work. However, Women’s Travel Patterns itself doesn’t process to the end. I'm attaching the error message and temporary files.

I think this will ease your work and please narrow down the debugging process and focus on the WTP issue. Also, ensure that the thresholds for the entire Accessibility domain have been adjusted accordingly. After an internal review and QC, please let us know the status. Considering the above, when can we expect the Accessibility dimension to be ready?

Looking forward to your reply.

Thanks,
Dragos


[error.txt](https://github.com/user-attachments/files/16321053/error.txt)
[test 20072024.zip](https://github.com/user-attachments/files/16321052/test.20072024.zip)

**Comment by osundwajeff** [comment] 2024-07-21 20:49
Here's @mvmaltitz 

Hi @dragosgontariu, i was able to look into the issue and I worked on it. The team spearheaded by @javaftw will be able to review and test the updates. After that we will provide feedback.

**Comment by dragosgontariu** [comment] 2024-07-24 13:35
@osundwajeff @mvmaltitz @ClaraIV @carolinamayh 

Hi Jeff,

Could you please change the default thresholds for:

1. WTF: 

0 to 400 meters: 5
401 to 800 meters: 4
801 to 1200 meters: 3
**1201 to 1500 meters: 2**
1501 to 2000 meters: 1
Over 2000 meters: 0

currently is like this:

![Image](https://github.com/user-attachments/assets/eaf7ce76-9f07-444e-815d-a9f893ddd218)

2. Health facilities:

0 to 2,000 meters: 5
2,001 to 4,000 meters: 4
4,001 to 6,000 meters: 3
6,001 to 8,000 meters: 2
8,001 to 10,000 meters: 1
Over 10,000 meters: 0

currently is like this:

![Image](https://github.com/user-attachments/assets/c7e5bf47-f973-4af0-a105-fa4d38c1adbc)

Thanks,
Dragos

**Comment by javaftw** [comment] 2024-07-29 08:02
Review 29 Jul 2024

Women's Travel Patterns:
![Image](https://github.com/user-attachments/assets/84b8c423-b49c-4cff-aa73-017656fd6872)

Health Facilities:
![Image](https://github.com/user-attachments/assets/1b85a654-d562-4e7f-8fee-963d6d39b669)

**Closed** 2024-12-04 15:15 UTC
